version: '3.8'
services:
  db:
    image: mysql/mysql-server
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./database-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
  
  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata1:/usr/share/elasticsearch/data

  movies-api:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env
    command: ["/bin/sh", "-c", "./wait-for-script.sh db:3306 -- npm run prisma:migrate && npm run prisma:seed && node dist/main.js"]

volumes:
  db_data:
  esdata1:
